### ISSUE TITLE
Can't get jobs to run when cloning this project

### ISSUE THREAD

**Issue by eddgrant** [hmrc/jenkins-jobs#22]
Hey folks, happy new year!

More of a question than an issue. I am trying to get us up and running using the HMRC jenkins-job-builders project. I thought a good first step would be to clone this project and get it building in a local Jenkins instance. However when I try this I am getting a rather unfathomable exception.

Here's what I've done:  

* Spin up a Jenkins instance (v1.580.2) `docker run -p 8080:8080 -v /foo/jenkins-home:/var/jenkins_home jenkins:latest`
* Install Jenkins job DSL plugin (v1.38)
* Installed various other plugins (Git, Github etc, nothing particularly unusual)
* Set up a seed job which clones this repository and does the following:
```
    Gradle Step
        Use Gradle Wrapper = true
        From Root Build Script Dir = true
        Tasks = clean build
    Process Jobs DSL Step
        Look On Filesystem = true
        DSL Scripts = jobs/**/*.groovy
        Removed Jobs = Delete
        Removed Views = Delete
        Context To Use For Relative Job Names = Jenkins Root
        Additional Classpath = build/libs/*.jar
```
When I run the seed job it fails with the following error:

```
ERROR: (JobBuilder.groovy, line 124) No signature of method: ci_open_jenkins.build.aoss.job() is applicable for argument types: (uk.gov.hmrc.jenkinsjobbuilders.domain.builder.JobBuilder$_build_closure1) values: [uk.gov.hmrc.jenkinsjobbuilders.domain.builder.JobBuilder$_build_closure1@43dde5e2]
Possible solutions: job(java.lang.String), job(java.lang.String, groovy.lang.Closure), run(), run(), any(), use([Ljava.lang.Object;)
Finished: FAILURE
```

Looking at line 124 it seems to call the script instance (which is cast in the script as a JobDslFactory). I'm wondering if some clever dynamic magic isn't happening which is resulting in the script instance not being given a `job()` method?

V grateful for any insight here.

Cheers,

Edd

**Comment by agilestevesmith** [comment]
Hi @eddgrant 

There was a typo in the first step of the seed-jenkins recommended setup, see https://github.com/hmrc/jenkins-job-builders/commit/4e138538211546597ebd3b7330f441155472284f. Perhaps that will help?

S

**Comment by eddgrant** [comment]
Hey @agilestevesmith ,

Thanks. No luck after trying that unfortunately. From what I can see the Jenkins plugin needs both `jenkins-jobs.jar` and `jenkins-job-builders-7.0.0.jar` on the classpath when seeding the jobs, so I've ended up running `./gradlew clean relativeDependencies build` in order to generate both of the jars. Unfortunately I still get the same error.

Interestingly it only occurs when I'm trying to use the HMRC builders, if I just get it to execute a plain DSL script it works just fine.

Out of interest what version of the job DSL Jenkins plugin are you running at the moment?

**Comment by agilestevesmith** [comment]
1.29 https://github.com/hmrc/jenkins-job-builders/blob/master/build.gradle#L24

**Comment by eddgrant** [comment]
hmm, that's interesting, Jenkins installed v1.38 of the plugin for me and won't let me downgrade to 1.29. Furthermore I couldn't find a corresponding version of the dependency in bintray e.g. https://bintray.com/jenkins/maven/plugins%3Ajob-dsl-core/1.38/view

Will try uninstalling the plugin and manually installing the v1.29 hpi file to see if that makes any difference.

**Comment by eddgrant** [comment]
ok that's sorted it (manually installing the specific version of the HPI file). So I guess the issue lies in the fact that there's no bintray artefact for v1.38. Will get a ticket raised with the plugin folks.

Cheers dude.
